name: Build Index JSON

on:
  push:
    paths:
      - 'Schema/**/outputs/**'
      - 'Scripts/generar_index.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script to generate index.json
        run: python Scripts/generar_index.py

      - name: Commit and push updated index.json
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.json
          git commit -m "🔄 Auto-update index.json" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:${{ github.ref }}
